### WeatherLens India Project_datacleaning

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Internships/projects/data/india_2000_2024_daily_weather.csv")
df.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,Delhi,01-01-2000,19.9,7.4,19.2,5.8,0.0,0.0,0,10.9,13.3,58
1,Delhi,02-01-2000,20.0,5.5,18.9,3.4,0.0,0.0,3,9.5,14.8,326
2,Delhi,03-01-2000,20.1,6.3,18.2,4.3,0.0,0.0,0,10.0,23.8,309
3,Delhi,04-01-2000,19.8,6.4,18.5,4.2,0.0,0.0,0,8.6,18.7,311
4,Delhi,05-01-2000,19.4,5.3,17.7,3.2,0.0,0.0,0,9.4,20.2,322

In [4]:
df.shape

(91320, 12)

In [5]:
df.columns.tolist()

['city',
 'date',
 'temperature_2m_max',
 'temperature_2m_min',
 'apparent_temperature_max',
 'apparent_temperature_min',
 'precipitation_sum',
 'rain_sum',
 'weather_code',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant']

In [7]:
df.dtypes

city                               str
date                               str
temperature_2m_max             float64
temperature_2m_min             float64
apparent_temperature_max       float64
apparent_temperature_min       float64
precipitation_sum              float64
rain_sum                       float64
weather_code                     int64
wind_speed_10m_max             float64
wind_gusts_10m_max             float64
wind_direction_10m_dominant      int64
dtype: object

In [8]:
df.isnull().sum()

city                           0
date                           0
temperature_2m_max             0
temperature_2m_min             0
apparent_temperature_max       0
apparent_temperature_min       0
precipitation_sum              0
rain_sum                       0
weather_code                   0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
dtype: int64

In [9]:
print(df[['precipitation_sum', 'rain_sum']].describe())
print("---")
print((df['precipitation_sum'] == df['rain_sum']).value_counts())

       precipitation_sum      rain_sum
count       91320.000000  91320.000000
mean            3.092751      3.092751
std             9.164448      9.164448
min             0.000000      0.000000
25%             0.000000      0.000000
50%             0.000000      0.000000
75%             1.700000      1.700000
max           339.900000    339.900000
---
True    91320
Name: count, dtype: int64

In [10]:
print(df['weather_code'].value_counts())

weather_code
3     21527
0     15544
51    12403
63     8483
1      8215
2      8031
61     6826
53     6647
55     2454
65     1190
Name: count, dtype: int64

In [11]:
# If rain_sum > 0 → it rained (1)
# If rain_sum == 0 → no rain (0)
df['rain_tomorrow'] = (df['rain_sum'] > 0).astype(int)
print(df['rain_tomorrow'].value_counts())

rain_tomorrow
0    53317
1    38003
Name: count, dtype: int64

In [14]:
print(df['city'].unique())

<ArrowStringArray>
[    'Delhi',    'Mumbai',   'Kolkata',   'Chennai', 'Bangalore', 'Hyderabad',
 'Ahmedabad',      'Pune',    'Jaipur',   'Lucknow']
Length: 10, dtype: str

In [15]:
print(df['city'].value_counts())

city
Delhi        9132
Mumbai       9132
Kolkata      9132
Chennai      9132
Bangalore    9132
Hyderabad    9132
Ahmedabad    9132
Pune         9132
Jaipur       9132
Lucknow      9132
Name: count, dtype: int64

In [16]:
weather_map = {
    0: 'Clear', 1: 'Mainly Clear', 
    2: 'Partly Cloudy',
    3: 'Overcast',
    51: 'Light Drizzle', 
    53: 'Moderate Drizzle',
    55: 'Dense Drizzle', 
    61: 'Slight Rain',
    63: 'Moderate Rain',
    65: 'Heavy Rain'
}

df['weather_condition'] = df['weather_code'].map(weather_map)
print(df['weather_condition'].value_counts())

weather_condition
Overcast            21527
Clear               15544
Light Drizzle       12403
Moderate Rain        8483
Mainly Clear         8215
Partly Cloudy        8031
Slight Rain          6826
Moderate Drizzle     6647
Dense Drizzle        2454
Heavy Rain           1190
Name: count, dtype: int64

In [19]:
df.columns.tolist()

['city',
 'date',
 'temperature_2m_max',
 'temperature_2m_min',
 'apparent_temperature_max',
 'apparent_temperature_min',
 'precipitation_sum',
 'rain_sum',
 'weather_code',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant',
 'rain_tomorrow',
 'weather_condition']

In [ ]:
df.drop(columns=['precipitation_sum'], inplace=True)

In [25]:
df.columns.tolist()

['city',
 'date',
 'temperature_2m_max',
 'temperature_2m_min',
 'apparent_temperature_max',
 'apparent_temperature_min',
 'rain_sum',
 'weather_code',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant',
 'rain_tomorrow',
 'weather_condition']

In [28]:
df.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,rain_tomorrow,weather_condition
0,Delhi,01-01-2000,19.9,7.4,19.2,5.8,0.0,0,10.9,13.3,58,0,Clear
1,Delhi,02-01-2000,20.0,5.5,18.9,3.4,0.0,3,9.5,14.8,326,0,Overcast
2,Delhi,03-01-2000,20.1,6.3,18.2,4.3,0.0,0,10.0,23.8,309,0,Clear
3,Delhi,04-01-2000,19.8,6.4,18.5,4.2,0.0,0,8.6,18.7,311,0,Clear
4,Delhi,05-01-2000,19.4,5.3,17.7,3.2,0.0,0,9.4,20.2,322,0,Clear

In [30]:
df['date'] = pd.to_datetime(df['date'], dayfirst=True)

In [31]:
print(df['date'].head(5))
print(df['date'].dtype)

0   2000-01-01
1   2000-01-02
2   2000-01-03
3   2000-01-04
4   2000-01-05
Name: date, dtype: datetime64[us]
datetime64[us]

In [32]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [33]:
df.columns.tolist()

['city',
 'date',
 'temperature_2m_max',
 'temperature_2m_min',
 'apparent_temperature_max',
 'apparent_temperature_min',
 'rain_sum',
 'weather_code',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant',
 'rain_tomorrow',
 'weather_condition',
 'year',
 'month',
 'day']

In [34]:
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Summer'
    elif month in [6, 7, 8, 9]:
        return 'Monsoon'
    elif month == 10:
        return 'Retreating Monsoon'
    elif month == 11:
        return 'Pre-Winter'

df['season'] = df['month'].apply(get_season)
print(df['season'].value_counts())

season
Monsoon               30500
Summer                23000
Winter                22570
Retreating Monsoon     7750
Pre-Winter             7500
Name: count, dtype: int64

In [35]:
df['temp_range'] = df['temperature_2m_max'] - df['temperature_2m_min']

In [38]:
df.shape

(91320, 18)

In [39]:
df.columns.tolist()

['city',
 'date',
 'temperature_2m_max',
 'temperature_2m_min',
 'apparent_temperature_max',
 'apparent_temperature_min',
 'rain_sum',
 'weather_code',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant',
 'rain_tomorrow',
 'weather_condition',
 'year',
 'month',
 'day',
 'season',
 'temp_range']

In [40]:
df.head(6)

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,rain_tomorrow,weather_condition,year,month,day,season,temp_range
0,Delhi,2000-01-01,19.9,7.4,19.2,5.8,0.0,0,10.9,13.3,58,0,Clear,2000,1,1,Winter,12.5
1,Delhi,2000-01-02,20.0,5.5,18.9,3.4,0.0,3,9.5,14.8,326,0,Overcast,2000,1,2,Winter,14.5
2,Delhi,2000-01-03,20.1,6.3,18.2,4.3,0.0,0,10.0,23.8,309,0,Clear,2000,1,3,Winter,13.8
3,Delhi,2000-01-04,19.8,6.4,18.5,4.2,0.0,0,8.6,18.7,311,0,Clear,2000,1,4,Winter,13.4
4,Delhi,2000-01-05,19.4,5.3,17.7,3.2,0.0,0,9.4,20.2,322,0,Clear,2000,1,5,Winter,14.1
5,Delhi,2000-01-06,19.2,6.0,16.2,3.6,0.0,0,15.3,30.6,303,0,Clear,2000,1,6,Winter,13.2

In [41]:
df.drop(columns=['weather_code'], inplace=True)

Final shape: (91320, 17)
Final columns: ['city', 'date', 'temperature_2m_max', 'temperature_2m_min', 'apparent_temperature_max', 'apparent_temperature_min', 'rain_sum', 'wind_speed_10m_max', 'wind_gusts_10m_max', 'wind_direction_10m_dominant', 'rain_tomorrow', 'weather_condition', 'year', 'month', 'day', 'season', 'temp_range']

In [42]:
print("Final shape:", df.shape)

Final shape: (91320, 17)

In [43]:
df.columns.tolist()

['city',
 'date',
 'temperature_2m_max',
 'temperature_2m_min',
 'apparent_temperature_max',
 'apparent_temperature_min',
 'rain_sum',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant',
 'rain_tomorrow',
 'weather_condition',
 'year',
 'month',
 'day',
 'season',
 'temp_range']

In [48]:
df.to_csv('clean_weather.csv', index=False)

In [46]:
import os
print(os.path.exists('clean_weather.csv'))  # Should print True

True

In [47]:
import os
print(os.getcwd())

C:\Users\Apurva Malankar